services:

  corteza:
    image: cortezaproject/corteza:2023.9.1
    restart: unless-stopped
    env_file:
      - .env 
    depends_on: 
      - db 
    ports: 
      - "18080:80" 

  db:
    image: postgres:15
    restart: unless-stopped
    healthcheck: { test: ["CMD-SHELL", "pg_isready -U corteza"], interval: 10s, timeout: 5s, retries: 5 }
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=corteza
      - POSTGRES_PASSWORD=corteza

      
