services:

  server:
    image: cortezaproject/corteza-server:2023.9
    restart: unless-stopped
    env_file: .env 
    depends_on: 
      - db
      - corredor 
    ports: 
      - "8200:80"

  corredor:
    image: cortezaproject/corteza-server-corredor:2023.9
    restart: unless-stopped
    env_file: .env 

  db:
    image: mariadb           #percona:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_RANDOM_ROOT_PASSWORD=random 

      